# ===================================================================
# Configuração do GodMode-MCtrilhas
# Aqui você pode definir todas as insígnias e suas recompensas.
# ===================================================================

badges:
  # ID único da insígnia. Usado em comandos como /scout removebadge.
  lumberjack:
    # Nome da insígnia que aparece para o jogador.
    name: "Insígnia de Lenhador"
    # Descrição que aparece para o jogador.
    description: "Corte 100 árvores."
    # Quantidade de ações necessárias para conquistar a insígnia.
    required-progress: 100
    # Seção de recompensas. Todos os campos aqui são opcionais.
    rewards:
      totems: 50
      item: "minecraft:diamond_axe{Enchantments:[{id:'minecraft:efficiency',lvl:2}]}"
      amount: 1

  miner:
    name: "Insígnia de Minerador"
    description: "Minere 500 blocos de pedra ou minérios."
    required-progress: 500
    rewards:
      totems: 100
      item: "minecraft:diamond_pickaxe{Enchantments:[{id:'minecraft:fortune',lvl:1}]}"
      amount: 1

  cook:
    name: "Insígnia de Cozinheiro"
    description: "Cozinhe 50 alimentos."
    required-progress: 50
    rewards:
      totems: 50
      item: "minecraft:bread"
      amount: 10

  builder:
    name: "Insígnia de Construtor"
    description: "Coloque 1000 blocos de construção."
    required-progress: 1000
    rewards:
      totems: 150
