# Arquivo de configuração para o MCTrilhas.
# Use este arquivo para definir as insígnias, suas recompensas e requisitos.

# Formato da mensagem de progresso.
# Placeholders disponíveis: {badgeName}, {progress}, {required}, {percentage}
progress-message-format: "&e{badgeName}: &a{progress}&8/&7{required} &b({percentage}%)"

# Formato da mensagem de conquista de insígnia.
# Placeholders: {badgeName}
award-message:
  - "&6&l[INSÍGNIA DESBLOQUEADA]"
  - "&eParabéns! Você conquistou a insígnia {badgeName}!"

# Seção onde todas as insígnias são definidas.
badges:
  # Ativa a interface gráfica (GUI) para o comando /scout badges.
  # Se for 'false' ou não existir, as insígnias serão mostradas no chat.
  use-gui: true

  lumberjack:
    name: "Insígnia de Lenhador"
    description: "Corte 10000 árvores."
    reward-totems: 500
    required-progress: 10000
    # Lista de materiais ou tags que contam para o progresso.
    # Use "TAG:<nome_da_tag>" para tags (ex: "TAG:LOGS")
    # Use o nome do material para blocos específicos (ex: "OAK_PLANKS")
    tracked-items:
      - "TAG:LOGS"
    reward-item-data:
      material: "DIAMOND_AXE"
      amount: 1
      name: "&bMachado do Lenhador"
      lore:
        - "&7Eficiência aprimorada para o trabalho."
      enchantments:
        - "efficiency:2"
        - "unbreaking:1"

  miner:
    name: "Insígnia de Minerador"
    description: "Minere 50000 blocos de pedra ou minérios."
    reward-totems: 1000
    required-progress: 50000
    # Lista de materiais ou tags que contam para o progresso.
    tracked-items:
      - "TAG:STONE_ORE_REPLACEABLES" # Cobre Stone, Deepslate, Andesite, etc.
      - "TAG:COAL_ORES"
      - "TAG:IRON_ORES"
      - "TAG:COPPER_ORES"
      - "TAG:GOLD_ORES"
      - "TAG:REDSTONE_ORES"
      - "TAG:LAPIS_ORES"
      - "TAG:DIAMOND_ORES"
      - "TAG:EMERALD_ORES"
    reward-item-data:
      material: "DIAMOND_PICKAXE"
      amount: 1
      name: "&9Picareta do Minerador"
      lore:
        - "&7Que a sorte esteja com você."
      enchantments:
        - "fortune:1"
        - "unbreaking:1"

  cook:
    name: "Insígnia de Cozinheiro"
    description: "Cozinhe 5000 itens."
    reward-totems: 500
    required-progress: 5000
    reward-item-data:
      material: "SMOKER"
      amount: 1
      name: "&6Defumador do Chef"
      lore:
        - "&7Cozinhe seus alimentos duas vezes mais rápido."
      enchantments: [] # Adicionado para consistência

  builder:
    name: "Insígnia de Construtor"
    description: "Coloque 80000 blocos."
    reward-totems: 1500
    required-progress: 80000
    reward-item-data:
      material: "SHULKER_BOX"
      amount: 1
      name: "&dCaixa do Construtor"
      lore:
        - "&7Para guardar todos os seus materiais."
      enchantments: [] # Adicionado para consistência

  fishing:
    name: "Insígnia de Pescador"
    description: "Pesque 250 peixes."
    required-progress: 250
    reward-totems: 75
    reward-item-data:
      material: "FISHING_ROD"
      amount: 1
      name: "&bVara de Pescar do Mestre Pescador"
      lore:
        - "&7Uma vara especial para um"
        - "&7pescador exemplar."
      enchantments:
        - "lure:2"
        - "unbreaking:1"

  farming:
    name: "Insígnia de Agricultor"
    description: "Colha 5000 itens de plantações."
    required-progress: 5000
    reward-totems: 500
    # Itens que contam para o progresso. O listener irá verificar se o bloco quebrado é um desses.
    # O listener também deve verificar se a cultura está totalmente crescida.
    tracked-items:
      - "WHEAT"
      - "CARROTS"
      - "POTATOES"
      - "BEETROOTS"
      - "NETHER_WART"
      - "MELON"
      - "PUMPKIN"
    reward-item-data:
      material: "DIAMOND_HOE"
      amount: 1
      name: "&aEnxada do Agricultor"
      lore:
        - "&7Para colheitas abundantes."
      enchantments:
        - "fortune:2"
        - "unbreaking:1"

  crafting:
    name: "Insígnia de Artesão"
    description: "Crie 1000 itens na bancada de trabalho."
    required-progress: 1000
    reward-totems: 750
    reward-item-data:
      material: "CRAFTING_TABLE"
      amount: 1
      name: "&6Bancada de Trabalho do Mestre"
      lore:
        - "&7Criações mais rápidas e eficientes."

  explorer:
    name: "Insígnia de Explorador"
    description: "Visite 25 biomas diferentes."
    required-progress: 25
    reward-totems: 1000
    reward-item-data:
      material: "COMPASS"
      amount: 1
      name: "&aBússola do Explorador"
      lore:
        - "&7Nunca se perca em suas aventuras."
      enchantments:
        - "unbreaking:3"

# Recompensa diária para os jogadores
daily-reward:
  enabled: true
  cooldown-hours: 24
  reward-totems: 25
  reward-item-data:
    material: "GOLDEN_APPLE"
    amount: 1
    name: "&6Maçã Dourada Diária"
    lore:
      - "&7Um presente por sua dedicação!"
    enchantments: [] # Sem encantamentos para a maçã
  messages:
    claim-success: "&aVocê coletou sua recompensa diária! Volte amanhã para mais."
    cooldown: "&cVocê já coletou sua recompensa. Tente novamente em &e{time}&c."
    login-notification: "&a[!] Sua recompensa diária está disponível! Use &e/daily&a para coletar."