name: GodModeMCTrilhas
version: '${project.version}'
main: com.magnocat.godmode.GodModePlugin
api-version: '1.20'
authors: [MagnoCat]
description: Plugin para o servidor MC Trilhas com temática escoteira.
website: https://github.com/magnocat/GodMode-MCTrilhas
softdepend: [Vault, WorldGuard]

commands:
  scout:
    description: Comando principal do plugin de escoteiros.
    usage: "/<command> [subcommand]"
    aliases: [trilhas, insignia, escoteiro]
  daily:
    description: Coleta a recompensa diária de Totens.
    usage: /<command>
    permission: godmode.scout.daily
    aliases: [recompensa, reward]
    permission-message: "§cVocê não tem permissão para usar este comando."

permissions:
  godmode.scout.*:
    description: Dá acesso a todos os comandos do GodMode-MCtrilhas.
    children:
      godmode.scout.use: true
      godmode.scout.daily: true
      godmode.scout.admin: true
      godmode.scout.progress.other: true
  godmode.scout.use:
    description: Permite ao jogador ver suas próprias insígnias e progresso.
    default: true
  godmode.scout.daily:
    description: Permite ao jogador coletar a recompensa diária.
    default: true
  godmode.scout.admin:
    description: Permite acesso aos comandos administrativos, como remover insígnias.
    default: op
  godmode.scout.progress.other:
    description: Permite ver o progresso de outros jogadores.
    default: op