name: GodMode-MCtrilhas
version: '${project.version}' # Pega a versão do pom.xml
main: com.magnocat.godmode.GodModePlugin
api-version: '1.21'
author: MagnoCat
description: Plugin para o servidor MC Trilhas com temática escoteira.
website: https://github.com/magnocat/GodMode-MCTrilhas
softdepend: [Vault] # Dependência opcional, o plugin carregará mesmo sem o Vault