# Este workflow automatiza o processo de build e criação de um Release no GitHub.
# Ele é acionado sempre que uma nova tag começando com 'v' (ex: v1.0, v1.2.1) é enviada.
name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    # Usa a versão mais recente do Ubuntu para executar o job
    runs-on: ubuntu-latest
    # Concede permissões para a action criar um release
    permissions:
      contents: write

    steps:
      # Passo 1: Faz o checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Configura o JDK 17 (Temurin), conforme especificado na sua documentação
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Adiciona cache para as dependências do Maven, acelerando os builds

      # Passo 3: Compila o projeto com o Maven, criando o arquivo .jar
      - name: Build with Maven
        run: mvn clean package --file pom.xml

      # Passo 4: Cria um novo Release no GitHub e anexa o .jar compilado
      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          # Usa um wildcard para encontrar o .jar, evitando erros quando a versão muda
          files: target/*.jar
